### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by googooog** [Dimlitter/jd_AutoComment#16]
sy@shiyangdeMini jd_AutoComment % python3 auto_comment_plus.py
开始京东批量评价！

Traceback (most recent call last):
  File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 368, in <module>
    main(opts)
  File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 339, in main
    N = No(opts)
  File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 329, in No
    N = all_evaluate(opts)
  File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 123, in all_evaluate
    req = requests.get(url, headers=headers)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1326, in _send_request
    self.putheader(hdr, value)
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1258, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2018' in position 4: ordinal not in range(256)
sy@shiyangdeMini jd_AutoComment % python3 auto_comment_plus.py
开始京东批量评价！

Traceback (most recent call last):
  File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 368, in <module>
    main(opts)
  File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 339, in main
    N = No(opts)
  File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 329, in No
    N = all_evaluate(opts)
  File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 123, in all_evaluate
    req = requests.get(url, headers=headers)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1326, in _send_request
    self.putheader(hdr, value)
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1258, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2018' in position 4: ordinal not in range(256)

**Comment by happyskey** [comment]
一样的，前天还能用

**Comment by LittleYe233** [comment]
> sy@shiyangdeMini jd_AutoComment % python3 auto_comment_plus.py 开始京东批量评价！
> 
> Traceback (most recent call last): File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 368, in main(opts) File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 339, in main N = No(opts) File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 329, in No N = all_evaluate(opts) File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 123, in all_evaluate req = requests.get(url, headers=headers) File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 75, in get return request('get', url, params=params, **kwargs) File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request return session.request(method=method, url=url, **kwargs) File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request resp = self.send(prep, **send_kwargs) File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send r = adapter.send(request, **kwargs) File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send resp = conn.urlopen( File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request conn.request(method, url, **httplib_request_kw) File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request self._send_request(method, url, body, headers, encode_chunked) File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1326, in _send_request self.putheader(hdr, value) File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 224, in putheader _HTTPConnection.putheader(self, header, *values) File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1258, in putheader values[i] = one_value.encode('latin-1') UnicodeEncodeError: 'latin-1' codec can't encode character '\u2018' in position 4: ordinal not in range(256) sy@shiyangdeMini jd_AutoComment % python3 auto_comment_plus.py 开始京东批量评价！
> 
> Traceback (most recent call last): File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 368, in main(opts) File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 339, in main N = No(opts) File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 329, in No N = all_evaluate(opts) File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 123, in all_evaluate req = requests.get(url, headers=headers) File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 75, in get return request('get', url, params=params, **kwargs) File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request return session.request(method=method, url=url, **kwargs) File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request resp = self.send(prep, **send_kwargs) File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send r = adapter.send(request, **kwargs) File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send resp = conn.urlopen( File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request conn.request(method, url, **httplib_request_kw) File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request self._send_request(method, url, body, headers, encode_chunked) File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1326, in _send_request self.putheader(hdr, value) File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 224, in putheader _HTTPConnection.putheader(self, header, *values) File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1258, in putheader values[i] = one_value.encode('latin-1') UnicodeEncodeError: 'latin-1' codec can't encode character '\u2018' in position 4: ordinal not in range(256)

@googooog @happyskey 你们的 `config.yml` 里面有无非 ASCII 字符（如“…”）？

**Comment by googooog** [comment]
我更改了一下cookie，现在提示这个错误
开始京东批量评价！

待评价订单 47----待晒单 0----待追评 75----服务评价 63----已评价 0----
1.开始普通评价
当前共有47个评价。
Traceback (most recent call last):
  File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 368, in <module>
    main(opts)
  File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 345, in main
    N = ordinary(N, opts)
  File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 156, in ordinary
    oid = Order.xpath('tr[@class="tr-th"]/td/span[3]/a/text()')[0]
IndexError: list index out of range

**Comment by LittleYe233** [comment]
> 我更改了一下cookie，现在提示这个错误 开始京东批量评价！
> 
> 待评价订单 47----待晒单 0----待追评 75----服务评价 63----已评价 0---- 1.开始普通评价 当前共有47个评价。 Traceback (most recent call last): File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 368, in main(opts) File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 345, in main N = ordinary(N, opts) File "/Users/sy/jd_AutoComment/auto_comment_plus.py", line 156, in ordinary oid = Order.xpath('tr[@Class="tr-th"]/td/span[3]/a/text()')[0] IndexError: list index out of range

和 #10 是类似的。会在后续提交中修复。
