### ISSUE TITLE
不能晒单

### ISSUE THREAD

**Issue by happy-Z** [Dimlitter/jd_AutoComment#29]
INFO     开始京东批量评价！
2022-10-08 00:49:21,822 INFO
2022-10-08 00:49:22,062 WARNING  Can't find num content in XPath, fallback to 0
2022-10-08 00:49:22,063 WARNING  Can't find num content in XPath, fallback to 0
2022-10-08 00:49:22,063 INFO     待评价订单 0----待追评 19----服务评价 30----已评价 0
2022-10-08 00:49:22,064 INFO
Traceback (most recent call last):
  File "auto_comment_plus.py", line 689, in <module>
    main(opts)
  File "auto_comment_plus.py", line 556, in main
    if N['待晒单'] != 0:
KeyError: '待晒单'

**Comment by Cyiming** [comment]
同样错误

**Comment by githubfat** [comment]
我把晒单相关代码都删了，可以运行了
