### ISSUE TITLE
获取图片有报错

### ISSUE THREAD

**Issue by rootphantomer** [Dimlitter/jd_AutoComment#49]
使用beta分支导致获取图片报错

**Comment by rootphantomer** [comment]
```
2024-01-04 21:35:44,750 INFO 开始获取图片
Traceback (most recent call last):
File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\simplejson_init_.py", line 525, in loads
return _default_decoder.decode(s)
File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\simplejson\decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "E:\jd_AutoComment-main\auto_comment_plus.py", line 783, in
main(opts)
File "E:\jd_AutoComment-main\auto_comment_plus.py", line 611, in main
N = ordinary(N, opts)
File "E:\jd_AutoComment-main\auto_comment_plus.py", line 270, in ordinary
imgdata = req1.json()
File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by rootphantomer** [comment]
最新main代码自测评价后没发现问题，故issue关闭。
