### ISSUE TITLE
爬取不到评价信息

### ISSUE THREAD

**Issue by cy465728759** [Dimlitter/jd_AutoComment#50]
为啥商品名称回滚了，而且也爬取不到评价信息

## 开始执行... 2024-01-09 10:53:38

2024-01-09 10:53:52,260 [1;32mINFO[0m     开始京东批量评价！
2024-01-09 10:53:52,261 [1;32mINFO[0m     
2024-01-09 10:53:52,612 [1;32mINFO[0m     Can't find num content in XPath, fallback to 0
2024-01-09 10:53:52,614 [1;32mINFO[0m     待评价订单 52----待追评 176----服务评价 114----已评价 0
2024-01-09 10:53:52,614 [1;32mINFO[0m     
2024-01-09 10:53:52,615 [1;32mINFO[0m     已评价：0个
2024-01-09 10:53:52,615 [1;32mINFO[0m     1.开始普通评价
2024-01-09 10:53:53,674 [1;32mINFO[0m     当前共有52个评价。
2024-01-09 10:53:53,676 [1;32mINFO[0m     	0.开始评价订单	京东（JD）支付抽奖权益包[288436797959]并晒图
2024-01-09 10:53:54,131 [1;32mINFO[0m     爬取商品数量最多为8个,请耐心等待,也可以自行修改jdspider文件
2024-01-09 10:53:54,132 [1;33mWARNING[0m  已爬取0 条 positive 评价信息
2024-01-09 10:53:54,133 [1;32mINFO[0m     爬取的评价结果：[]
2024-01-09 10:53:54,133 [1;33mWARNING[0m  当前商品没有评价,使用默认评价
2024-01-09 10:54:01,532 [1;33mWARNING[0m  jieba textrank analysis error: list index out of range, name fallback to "宝贝"
2024-01-09 10:54:01,533 [1;32mINFO[0m     		评价内容,星级5：收到快递后迫不及待的拆了包装。宝贝我真的是非常喜欢不错不错！看了好几家店，也对比了好几家店，最后发现还是这一家的宝贝评价最好。拆开包装后惊艳到我了，这就是我想要的宝贝!包装的很精美！宝贝的质量和品质非常不错！真是一次愉快的购物！
2024-01-09 10:54:01,534 [1;32mINFO[0m     		开始获取图片
Traceback (most recent call last):
  File "/ql/scripts/6dylan6_jdm/auto_comment_plus.py", line 803, in <module>
    main(opts)
  File "/ql/scripts/6dylan6_jdm/auto_comment_plus.py", line 626, in main
    N = ordinary(N, opts)
  File "/ql/scripts/6dylan6_jdm/auto_comment_plus.py", line 277, in ordinary
    imgdata = req1.json()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

## 执行结束... 2024-01-09 10:54:03 耗时 25 秒

**Comment by rootphantomer** [comment]
京东（JD）支付抽奖权益包[288436797959]


这个貌似权益包一直有问题，先手动把这类商品自行评价一下吧。

**Comment by cy465728759** [comment]
换了一个商品，还是不行，爬不到评价

## 开始执行... 2024-01-09 11:59:01

2024-01-09 11:59:15,472 [1;32mINFO[0m     开始京东批量评价！
2024-01-09 11:59:15,473 [1;32mINFO[0m     
2024-01-09 11:59:15,883 [1;32mINFO[0m     Can't find num content in XPath, fallback to 0
2024-01-09 11:59:15,884 [1;32mINFO[0m     待评价订单 43----待追评 185----服务评价 104----已评价 0
2024-01-09 11:59:15,884 [1;32mINFO[0m     
2024-01-09 11:59:15,885 [1;32mINFO[0m     已评价：0个
2024-01-09 11:59:15,886 [1;32mINFO[0m     1.开始普通评价
2024-01-09 11:59:16,880 [1;32mINFO[0m     当前共有43个评价。
2024-01-09 11:59:16,882 [1;32mINFO[0m     	0.开始评价订单	太太乐 鲍汁蚝油 尝鲜装 65g 烧烤火锅蘸料炒菜  雀巢出品 [285192575039]并晒图
2024-01-09 11:59:17,390 [1;32mINFO[0m     爬取商品数量最多为8个,请耐心等待,也可以自行修改jdspider文件
2024-01-09 11:59:17,391 [1;33mWARNING[0m  已爬取0 条 positive 评价信息
2024-01-09 11:59:17,391 [1;32mINFO[0m     爬取的评价结果：[]
2024-01-09 11:59:17,392 [1;33mWARNING[0m  当前商品没有评价,使用默认评价
2024-01-09 11:59:24,761 [1;32mINFO[0m     		评价内容,星级5：不错不错！真是一次难忘的购物，这辈子没见过这么好用的东西！！快递超快！包装的很好！！很喜欢！！！我会推荐想买炒菜的朋友也来这家店里买收到货后我非常的开心，因为炒菜的质量和品质真的非常的好！看来看去最后还是选择了这家。
2024-01-09 11:59:24,762 [1;32mINFO[0m     		开始获取图片
2024-01-09 11:59:25,021 [1;32mINFO[0m     		图片url=//img30.360buyimg.com/shaidan/jfs/t1/249176/10/2451/174289/659bf297F962535b4/ef3b377c74d58d4f.jpg,//img30.360buyimg.com/shaidan/jfs/t1/237893/25/9835/154498/659bf297Ff323e7f3/70ea4d7a7f88c0e1.jpg

**Comment by rootphantomer** [comment]
@cy465728759 试试beta分支里的代码

**Comment by rootphantomer** [comment]
beta分支代码修复无评价的问题，自测评价没有问题，目前代码已经合并到main主线分支。
