### ISSUE TITLE
报错了，辛苦看下是什么原因

### ISSUE THREAD

**Issue by Cyiming** [Dimlitter/jd_AutoComment#69]
![Clip_2024-11-25_13-06-02](https://github.com/user-attachments/assets/b04fae69-40bf-4149-8394-2a070900f691)

**Comment by rootphantomer** [comment]
贴上完整日志。

**Comment by Cyiming** [comment]
> 贴上完整日志。

2024-11-25 13:05:46,611 INFO     开始京东批量评价！
2024-11-25 13:05:46,611 INFO     URL: https://club.jd.com/myJdcomments/myJdcomment.action?
2024-11-25 13:05:47,359 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 13:05:47,360 INFO     待评价订单 5----待追评 7----服务评价 13----已评价 0
2024-11-25 13:05:47,360 INFO     已评价：0个
2024-11-25 13:05:47,360 INFO     1.开始普通评价
2024-11-25 13:05:48,088 INFO     当前共有5个评价。
2024-11-25 13:05:48,089 INFO     	0.开始评价订单	骁途Mini1运动相机5K超强夜拍拇指相机裸机防水防抖摩托车记录仪第一视角穿戴vlog摄像机 标配版 无内存卡[301725978412]并晒图
2024-11-25 13:05:48,906 INFO     获取同类产品的搜索 url 结果：https://search.jd.com/Search?keyword=%E9%AA%81%E9%80%94Mini1%E8%BF%90%E5%8A%A8%E7%9B%B8%E6%9C%BA5K%E8%B6%85%E5%BC%BA%E5%A4%9C%E6%8B%8D%E6%8B%87%E6%8C%87%E7%9B%B8%E6%9C%BA%E8%A3%B8%E6%9C%BA%E9%98%B2%E6%B0%B4%E9%98%B2%E6%8A%96%E6%91%A9%E6%89%98%E8%BD%A6%E8%AE%B0%E5%BD%95%E4%BB%AA%E7%AC%AC%E4%B8%80%E8%A7%86%E8%A7%92%E7%A9%BF%E6%88%B4vlog%E6%91%84%E5%83%8F%E6%9C%BA%20%E6%A0%87%E9%85%8D%E7%89%88%20%E6%97%A0%E5%86%85%E5%AD%98%E5%8D%A1&enc=utf-8
2024-11-25 13:05:48,914 INFO     爬取商品数量最多为8个,请耐心等待,也可以自行修改jdspider文件
2024-11-25 13:05:48,915 WARNING  完了，self.productsId是空的，后面会导致默认评价了
Traceback (most recent call last):
  File "E:\CYZ\200 - code\别人代码\京东自动评价\jd_AutoComment-main\auto_comment_plus.py", line 909, in <module>
    main(opts)
  File "E:\CYZ\200 - code\别人代码\京东自动评价\jd_AutoComment-main\auto_comment_plus.py", line 724, in main
    N = ordinary(N, opts)
        ^^^^^^^^^^^^^^^^^
  File "E:\CYZ\200 - code\别人代码\京东自动评价\jd_AutoComment-main\auto_comment_plus.py", line 325, in ordinary
    xing, Str = generation(oname, opts=opts)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\CYZ\200 - code\别人代码\京东自动评价\jd_AutoComment-main\auto_comment_plus.py", line 169, in generation
    result = spider.getData(4, 3)  # 这里可以自己改
             ^^^^^^^^^^^^^^^^^^^^
  File "E:\CYZ\200 - code\别人代码\京东自动评价\jd_AutoComment-main\jdspider.py", line 136, in getData
    default_logger.info("sum_:" + str(sum_))
                                      ^^^^
UnboundLocalError: cannot access local variable 'sum_' where it is not associated with a value

**Comment by rootphantomer** [comment]
试试最新的 main 分支

**Comment by Cyiming** [comment]
> 试试最新的 main 分支

没有那个问题了 但有新问题了 服务单调不出循环了 我记得以前好像有过这个问题

2024-11-25 14:48:36,553 INFO     URL: https://club.jd.com/myJdcomments/myJdcomment.action?
2024-11-25 14:48:37,404 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:37,404 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:37,404 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:37,406 INFO     待评价订单 0----待追评 0----服务评价 13----已评价 0
2024-11-25 14:48:37,407 INFO     4.开始服务评价
2024-11-25 14:48:38,339 INFO     当前共有13个需要第一次服务评价。
2024-11-25 14:48:38,340 INFO     URL: https://club.jd.com/myJdcomments/myJdcomment.action?
2024-11-25 14:48:39,053 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:39,053 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:39,054 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:39,055 INFO     待评价订单 0----待追评 0----服务评价 13----已评价 0
2024-11-25 14:48:39,055 INFO     全部完成啦！
2024-11-25 14:48:39,055 WARNING  出现了二次错误，跳过了部分，重新尝试
2024-11-25 14:48:39,055 INFO     开始京东批量评价！
2024-11-25 14:48:39,056 INFO     URL: https://club.jd.com/myJdcomments/myJdcomment.action?
2024-11-25 14:48:39,789 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:39,789 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:39,790 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:39,791 INFO     待评价订单 0----待追评 0----服务评价 13----已评价 0
2024-11-25 14:48:39,791 INFO     已评价：0个
2024-11-25 14:48:39,791 INFO     4.开始服务评价
2024-11-25 14:48:40,667 INFO     当前共有13个需要第一次服务评价。
2024-11-25 14:48:40,669 INFO     URL: https://club.jd.com/myJdcomments/myJdcomment.action?
2024-11-25 14:48:41,408 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:41,409 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:41,409 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:41,413 INFO     待评价订单 0----待追评 0----服务评价 13----已评价 0
2024-11-25 14:48:41,413 INFO     全部完成啦！
2024-11-25 14:48:41,414 WARNING  出现了二次错误，跳过了部分，重新尝试
2024-11-25 14:48:41,414 INFO     开始京东批量评价！
2024-11-25 14:48:41,414 INFO     URL: https://club.jd.com/myJdcomments/myJdcomment.action?
2024-11-25 14:48:42,180 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:42,180 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:42,181 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:42,182 INFO     待评价订单 0----待追评 0----服务评价 13----已评价 0
2024-11-25 14:48:42,182 INFO     已评价：0个
2024-11-25 14:48:42,182 INFO     4.开始服务评价
2024-11-25 14:48:43,214 INFO     当前共有13个需要第一次服务评价。
2024-11-25 14:48:43,216 INFO     URL: https://club.jd.com/myJdcomments/myJdcomment.action?
2024-11-25 14:48:44,003 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:44,003 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:44,003 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:44,004 INFO     待评价订单 0----待追评 0----服务评价 13----已评价 0
2024-11-25 14:48:44,005 INFO     全部完成啦！
2024-11-25 14:48:44,005 WARNING  出现了二次错误，跳过了部分，重新尝试
2024-11-25 14:48:44,005 INFO     开始京东批量评价！
2024-11-25 14:48:44,005 INFO     URL: https://club.jd.com/myJdcomments/myJdcomment.action?
2024-11-25 14:48:44,675 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:44,675 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:44,676 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:44,677 INFO     待评价订单 0----待追评 0----服务评价 13----已评价 0
2024-11-25 14:48:44,677 INFO     已评价：0个
2024-11-25 14:48:44,677 INFO     4.开始服务评价
2024-11-25 14:48:45,538 INFO     当前共有13个需要第一次服务评价。
2024-11-25 14:48:45,540 INFO     URL: https://club.jd.com/myJdcomments/myJdcomment.action?
2024-11-25 14:48:46,254 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:46,254 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:46,254 INFO     Can't find num content in XPath, fallback to 0
2024-11-25 14:48:46,256 INFO     待评价订单 0----待追评 0----服务评价 13----已评价 0
2024-11-25 14:48:46,256 INFO     全部完成啦！
2024-11-25 14:48:46,256 WARNING  出现了二次错误，跳过了部分，重新尝试

**Comment by rootphantomer** [comment]
那就手工取消软件运行吧。
